apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  replicas: 3
  selector:
    matchLabels:
      service: api-feed
  template:
    metadata:
      labels:
        service: api-feed
    spec:
      containers:
      - name: api-feed
        image: karim2324/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: env-configmap
        volumeMounts:
        - name: aws-secret
          mountPath: /root/.aws
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
