apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: karim3032/udagram-api-feed:v2
        name: udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: URL
          value: "http://localhost:8100"
        - name: AWS_BUCKET
          value: "project3.buckett"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_REGION
          value: "us-east-1"
        - name: JWT_SECRET
          value: "testing"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_HOST
          value: "database-2.coyxlu9hcohi.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_PASSWORD
          value: "Km12345678"
        - name: POSTGRES_USERNAME
          value: "karim"
        volumeMounts:
        - name: aws-config-volume
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-config-volume
          configMap:
            name: aws-secret2