apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-feed
  name: api-feed-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP 
  selector:
    service: api-feed  # Corrected label to match your deployment labels
