
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed

# Tagging
- docker tag udagram-api-feed karim3032/udagram-api-feed:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push karim3032/udagram-api-feed:v1



# for udagram-api-user

- docker build -t udagram-api-user ./udagram-api-user

# Tagging
- docker tag udagram-api-user karim3032/udagram-api-user:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push karim3032/udagram-api-user:v1



## for udagram frontend 

- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-frontend karim3032/udagram-frontend:v1
  
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push karim3032/udagram-frontend:v1



# for reverseproxy nginx

- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-reverseproxy karim3032/udagram-reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push karim3032/udagram-reverseproxy:v1
