apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-user
  template:
    metadata:
      labels:
        service: api-user
    spec:
      containers:
      - image: karim3032/udagram-api-user:v2
        name: api-user
        imagePullPolicy: Always
        ports: 
        - containerPort: 8080
        env:
        - name: URL
          value: "http://localhost:8100"
        - name: AWS_BUCKET
          value: "project3.buckett"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_REGION
          value: "us-east-1"
        - name: JWT_SECRET
          value: "testing"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_HOST
          value: "database-2.coyxlu9hcohi.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_PASSWORD
          value: "Km12345678"
        - name: POSTGRES_USERNAME
          value: "karim"