kind: ConfigMap 
apiVersion: v1 
metadata:
  name: aws-secret 
data:
  # Configuration values can be set as key-value properties
  aws_access_key_id: ASIA52K3UU7DSAGZVPE2
  aws_secret_access_key: uVJoD5yVXmDMoI26BSpxy/bVReVvsKyJSm9RaAXT
  aws_session_token: FwoGZXIvYXdzEAMaDGna1edaI959n0z0vyLVATgPQ0F9MlHTBZPi/BaLj/1Ji6Hl4zyJPRZ3VNgtB38Uw4XZ6DVqjPFLoo4mc+SW1qxTf5xC87a0UUWr7KDcNKZF6q7MvaDHI+PGEfRamSX06SvkC9JhxZVPNnobGzgFzXdtbL8bViOlMscyTF9EgSbHj6U2YnXUf/7Ld4cm8lFzuXYRDPG0oOPE9rIpRxFZ//aY6lLTNjOUaJIljjLHhpGVrQKZoO9UMksoRc8ibogwTJL67ODob8U85yenKLiKJcKG7AeHN3ejxc9SRyP81hY8GHpw5SiZ/b2cBjIt7ZxAXQ3KEk6mA46bK2IX6FLMUmwNIoh8fcjyUdV18jU5zh/K8EBVEtuTb32r