version: 0.2

phases:
  pre_build:
    commands:
      # Add Docker login
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      # Build udagram-api-feed
      - docker build -t udagram-api-feed ./udagram-api-feed
      # Tagging
      - docker tag udagram-api-feed karim2324/udagram-api-feed:v9
      # Push to Docker Hub
      - docker push karim2324/udagram-api-feed:v9

      # Build udagram-api-user
      - docker build -t udagram-api-user ./udagram-api-user
      # Tagging
      - docker tag udagram-api-user karim2324/udagram-api-user:v9
      # Push to Docker Hub
      - docker push karim2324/udagram-api-user:v9

      # Build udagram-frontend
      - docker build -t udagram-frontend ./udagram-frontend
      # Tagging
      - docker tag udagram-frontend karim2324/udagram-frontend:v9
      # Push to Docker Hub
      - docker push karim2324/udagram-frontend:v9

      # Build udagram-reverseproxy
      - docker build -t udagram-reverseproxy ./udagram-reverseproxy
      # Tagging
      - docker tag udagram-reverseproxy karim2324/udagram-reverseproxy:v9
      # Push to Docker Hub
      - docker push karim2324/udagram-reverseproxy:v9

artifacts:
  files: []
