apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 3
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: karim2324/udagram-frontend:v7
        ports: 
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"
            memory: "64Mi"
