apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-user
  name: api-user-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP 
  selector:
    service: udagram-api-user
    